apiVersion: v1
kind: Service
metadata:
  name: tile-service
spec:
  selector:
    app: wiki-tiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      name: tilehttp
    - protocol: TCP
      port: 81
      targetPort: 8889
      name: articlehttp
  type: LoadBalancer

